### ISSUE TITLE
v0.8.19 onwards affect other libraries due to IntersectionObserver

### ISSUE THREAD

**Issue by stonehz** [timhagn/gatsby-background-image#105]
I will do my best to explain the issue but..
Using another component which sets event listeners (e.g. React Player for HTML5 videos)
is affected by the logic of the Intersection Observer and causes the weirdest thing ever....

the Video sound gets unmuted and continues playing despite moving to another page!!!

I've forked the provided example repo to show case how the video sound becomes unmuted due to the intersection observer setting of Gatsby-Background-Image.

**v0.8.19 works fine** and does not have this problem but all other versions beyond this one are causing the described side-effects!

How to reproduce
1. Clone repo https://github.com/stonehz/gbitest
2. run `yarn` and `yarn develop`
3. If you open `localhost:8000` you may see that the video is playing with sound. if not ,navigate to another page, e.g. 'Image-stack' and then return back.
4. The sound of the video will keep playing despite being on a different page, you can navigate to 'image-stack' again and you will keep hearing the sound of the video.

### Notes

Used latest Chrome and Firefox to test it (mainly Chrome)
the Video is set to autoplay as you can see from the props and Chrome requires that all autoplay videos are muted!
Source code for HTML5 video: https://github.com/CookPete/react-player/blob/master/src/players/FilePlayer.js

**Comment by timhagn** [comment]
Hi @stonehz,

sry for replying so late, but the last two weeks were quite taxing, as one might guess % ).
Gonna try digging into it this week : )!

Best,

Tim.

**Comment by stonehz** [comment]
Great thanks!
we use Intersection Observer from other plugins and is not affecting the video playback.
if you rollback to version `0.8.19` you will that it works without problem 😄

**Comment by timhagn** [comment]
Hi @stonehz,

I dare not hope that the just published `v1.0.0` might have whizzed your issue away ^^.
Quickly gave it a look (was quite busy with WFH during the week & preparing the major version today), though it doesn't seem as much has changed in the interim between `v0.8.19` & now (pertaining the IntersectionObserver).

Shouldn't it "magically" have fixed your issue, I'm gonna try working on it during the week % ).

Sry for the wait, nevertheless best wishes,

Tim.

**Comment by Mayaela** [comment]
I can confirm this issue, we've had many problems with video players since the update from 0.8.19. We've had the sound one and other errors with a hls player. This is a breaking change, it shouldn't happen on a simple update from 0.8 to 0.10. We hope for everyone that it will be fixed urgently since many people might not have realized they have such errors on production. We found out by chance after 5 days in production ! It's not an easy problem to catch if you don't test your full website and scenarios every day and we didn't expect a weird video problem to come from gatsby-image.

**Comment by timhagn** [comment]
Hi @Mayaela (& @stonehz),

this wasn't a breaking change (as how should I have foreseen it?) it's a bug, and I just declared it one. As you wrote, @Mayaela, it doesn't seem easy to catch and I've never experienced it on my Linux Workstation (or in Win / mac VMs). Might one of you share their `gatsby info`?
As I wrote, the diff didn't really show mayor differences in the IO handling, but with your help we're gonna catch at least this nasty one : )!

Best,

Tim.

**Comment by Mayaela** [comment]
We use gatsby-background-image-es5 and problems occur in development and production modes on any page with both an HTML video player and Background image components. If the player is at the top of the page and the background image further down the page, problems (anormal sound enabled, blob file not found for hls player) will be triggered only after scrolling to the background image component.

**Comment by timhagn** [comment]
Hi @stonehz & @Mayaela,

after finally finding the time to dig deeper, this should now be fixed with the just released
`gbi` `v1.1.1` : ).

Explanation:
It really had nothing to do with the IntersectionObeservers, but with introduction of Art-Directed images I had to find a way to correctly measure the components offset size. So I introduced a cloned body to get the Browser to calculate it for me. Sadly (as I only read now), the previously used `document.body.cloneNode(true)` also copies registered Event-Listeners & Observers % ).
Switching to a simple `document.createElement('body')` as a parent seems to have solved the issue while still calculating the correct `offsetWidth` & `offsetHeight` ^^.

Hope it works at your places, too! When it does, you may of course have the honor of closing this issue, @stonehz : ).

Best,

Tim.

**Comment by stonehz** [comment]
Thanks for your help @timhagn  and @Mayaela ..
i will test it on Monday and will close if everything is ok :+1:

**Comment by stonehz** [comment]
great job @timhagn  ,thanks for sorting this out. closing ticket
