### ISSUE TITLE
How to best control the size of generated images?

### ISSUE THREAD

**Issue by kimfucious** [timhagn/gatsby-background-image#26]
## Summary
First off, I want to say that I ❤️ this plug-in.  I've been waiting a long time for something like this, and am hopeful that it will prevent me from having to write long css files with multiple media query clauses, using image-set, etc.

That said, I'm seeing some behavior that has me confused.  Possibly, it's my implementation, or something that perhaps someone could shed some light on.

### Scenario

1. Simple setup using `<BackgroundImageSection/>` per the documentation
2. Original image format is jpg
3. Original image size < 200KB with a width of 1980px
4. Original image has been optimized using [Squoosh](https://squoosh.app) 
5. Component setup like the below

### Perceived Problems

1. Initially the base64 image is rendered as expected
2. It then fades out, leaving a blank background
3. After a pause the background image flashes once, then goes blank again
4. And finally, the background is displayed once more
5. The whole process takes > 6 seconds
6. Same behavior at any screen size

Here's the dev-tools network tab, which illustrates what's happening:
![image](https://user-images.githubusercontent.com/26792769/56850547-49dad100-692e-11e9-823c-7a57b1c58496.png)

Here's [a link to a live demo](https://gatsby-background-image.surge.sh/).

### Questions
I have the quality setting (see below) set to 100, and my expectation is that all generated images would be equal to or less than the size of the original, but the copies are actually larger.

The webp file is 419KB  (approx. 2.5x larger)
The jpg is 822KB (approx. 5x larger)

**Q1: What's the recommended setting here to ensure that generated images aren't growing larger than the original?**

It seems that two files (webp and jpg) file are downloaded simultaneously after the initial base64 image (first flash).  If caching is disabled (simulating an initial load of the page for a first time user) the webp file downloads a seconds time (using Chrome on Windows).

So in the worst case scenario (first time user) there are three transitions: from base 64, to webp, to (same) webp, with blank screens in between.  And two transitions (base64 to webp) for returning users with cache.

**Q2:  Is this expected behavior, or is there some setting that I've overlooked?  In other words, how can I prevent the background from flashing blank?"

```js
const BackgroundImageSection = ({ children }) => (
  <StaticQuery
    query={graphql`
      query {
        desktop: file(relativePath: { eq: "image.jpg" }) {
          childImageSharp {
            fluid(maxWidth: 1980, quality: 100) {
              ...GatsbyImageSharpFluid_withWebp
            }
          }
        }
      }
    `}
    render={data => {
      const imageData = data.desktop.childImageSharp.fluid;
      return (
        <BackgroundImage
          backgroundColor={"#000"}
          fluid={imageData}
          Tag="section"
          style={{
            backgroundPosition: "center",
            backgroundRepeat: "no-repeat",
            backgroundSize: "cover",
            height: "100vh",
            width: "100%",
          }}
        >
          <div className="d-flex flex-column vw-100 vh-100 align-items-center justify-content-center container">
            {children}
          </div>
        </BackgroundImage>
      );
    }}
  />
);
export default BackgroundImageSection;
```

### Environment (if relevant)

This is a clean setup from gatsby-default-starter, with the below plugins added:

```shell
    OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.13.0 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/bin/python
  npmPackages:
    gatsby: ^2.3.31 => 2.3.31
    gatsby-background-image: ^0.4.1 => 0.4.1
    gatsby-image: ^2.0.40 => 2.0.40
    gatsby-plugin-emotion: ^4.0.6 => 4.0.6
    gatsby-plugin-manifest: ^2.0.29 => 2.0.29
    gatsby-plugin-offline: ^2.0.25 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-resolve-src: ^2.0.0 => 2.0.0
    gatsby-plugin-sharp: ^2.0.35 => 2.0.35
    gatsby-source-filesystem: ^2.0.32 => 2.0.32
    gatsby-transformer-sharp: ^2.1.18 => 2.1.18
  npmGlobalPackages:
    gatsby-cli: 2.5.12
```

### File contents (if changed)

`package.json`: N/A

**Comment by timhagn** [comment]
Hi @kimfucious,

after a heartfelt Thank You for the compliment I owe you one. Because Wow(!) this is the most copious issue text I got since starting this : )!
Am outside at the moment but am gonna dig into it as soon as I'm back at my keyboard.
Till then,
Tim.

**Comment by kimfucious** [comment]
Cornicopius 😉

**Comment by timhagn** [comment]
Now let me have a look.

First off, though **Q1** would rather pertain `gatsby-plugin-sharp` or `gatsby-transformer-sharp` (as `gatsby-background-image` doesn't change the images sources it receives), I might be able to elaborate a little anyhow (as I'm just writing a plugin & transformer for gifs ; ):

`gatsby-plugin-sharp` internally uses `imagemin` with it's plugins for `-mozjpeg`, `-pngquant` and `-webp` respectively, after resize and other image operations have been done with `sharp` (so I'd guess nearly the same setup as squoosh.app) Setting the quality to 100 now nearly undoes most optimizations possible (especially for jpeg as a lossy format in the first place).
Try it for yourself in squoosh.app with their "Large Photo". Setting the quality to 100 gives me a 52% bigger image than the original with `MozJPEG` (Mozilla's initial answer to webp). WebP fares only a little better with still a 34% increase on highest "Effort" (multiple rounds and different encoding strategies). 

So I'd recommend values no higher than _90_ for quality (which gives me a 32% smaller WebP image even with "Effort" only set to 4) - I just changed the example values in `gbitest` and `gbi` accordingly.
For further minimization options have a look at `gatsby-plugin-sharp`'s [README](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sharp) especially the part about [Using MozJPEG](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sharp#using-mozjpeg).

Concerning **Q2** you are completely in the right place and are storming open doors 
(and it's mea culpa, not yours, as the behavior definitely wasn't planned thus ; ). 
But let me give you another round of thanks up front for the great demonstration page and your rundown through Network Tab's waterfall! 
It sadly looks like it would be better to implement a finite state machine for the different switching possibilities, after all. Cause, opposing to `gatsby-image`, we only have the two pseudo-elements to work with (and the issue was thought to be solved with #16 working with fallbacks etc... % ).
For starters the browser should never see the "optimized" jpeg at all when `_withWebp` has been chosen as a GraphQL fragment : /.

Gonna dig into it tomorrow and should you wanna ease my process beforehand, further rundowns with different `GatsbyImage...` fragments would be more than welcome ; )!

Thanks again for bringing this up,
greetz,

Tim.

P.S.: "Cornicopius"? There you've lost me (English isn't my native tongue after all ; ).

**Comment by timhagn** [comment]
OK, looked into it and I think I'm gonna "record" Mutations + States from `gatsby-image` / default `<picture />` elements and try to transfer the "finite" states to be "played back" in 
`gatsby-background-image`. Methinks the hardest part might be to determine which GraphQL-Fragment was being used for the `fixed` / `fluid` images, but it should be doable.
I'll keep ya posted - and as said before, help in determining the state-paths for the different `GatsbyImage...` fragments would be greatly appreciated : )!

**Comment by kimfucious** [comment]
Hi Tim,

Thanks for the gung-ho attitude toward working on this.  It and your excellent, informative replies are appreciated!

Regarding delays, I've done nothing intentional.  Ironically, I'm building this project anew with Gatsby 2.0, because my project on Gatsby 1 had a fabulous FOUC that no amount to setTimeOut and fadeIn from a blank screen could fix.  But again, I've implemented none of that here.  Maybe, what you're referring to is that I've set the background color on the html body to black (not sure)?

Here's some things I did:

- Made a "semi" clean install and put two huge image files in there (>5000px wide, and approx 6MB) and set the maxWidth to 5120 (highest iMac res for fun) and quality to 70.  When I went to publish that on surge, the size was 177980732 bytes!
- Squooshed the files to 1920 at 100% quality (< 3MB now).
- Deleted .cache and public, set the maxWidth to 1920 with quality of 70.
- Much better!
- Pushed to Surge

Regarding the components using gatsby-background-image, each section requires its own component, or least that's what I understand: that you can't use variables in Gatsby's query statements.  So you'll find two with separate queries for each respective bg image.  My plan is to use 5 on one page.

I now understand that running the package with 100% quality and a pre-optimized image isn't the way to go.  I'm assuming that the best way is to start with the original image and always use a lower quality than 100.

That said, the transitions/blanks are still visible in the demo and thus you should see them when you work with the repo.

> ☝️ Do note that this behavior doesn't exist in the local environment unless you turn on throttling (which takes > 10 seconds to render on Fast 3G).  It is always apparent when published/viewed to/from a web hosting provider (e.g. Surge).

The repo can be found [here ](https://github.com/kimfucious/gatsby-background-image-demo)and the demo site [here](http://gatsby-background-image.surge.sh/).

Let me know if I can be of any more help 😉

**Comment by timhagn** [comment]
Hi Kim,

another one I had to look up first (btw. you haven't told me what you meant by "Cornicopius" ; ):
"Gung Ho" seems to be an "americanism" I haven't heard / read before ^^. 
But it describes my attitude towards my "paquete pequeño" quite well, though "overzealous" in the Wiki definition seems a little over the top % ).

Anyways, I've cloned your repo, built it (after adding `typeface-exo-2` and `-sanchez` ; ) and (just to try something) published it on my own [hosting](https://devserv.timhagn.com). Only when accessing it via a VPN could I replicate the same transitions as on your surge one (but still faster; so you might wanna think about a different hosting - or are you on the free tier of surge? Then nevermind, though it might aggravate a potential FOUC ; ).
That's primarily what I was talking about (a bgColor should be working and never be visible when you've got a base64 image) as I only now thought about using my VPN for testing purposes and had not seen such a behavior until now % ).

Am now trying to profile the different transitioning steps from `gatsby-image` and build finite states for the different Fragments (trough a mixture of `MutationObserver` and React Dev Tools).

As soon as I'm finished with the first round (with the "default" `GatsbyImageSharpFluid` & `GatsbyImageSharpFluid_withWebp` Fragments) - and should you be willing to do it - I'd give you the code for the "state-profiler" so you could map the other available fragments out for me, while I implement a mini finite state machine (from here on: mFSM ; ) in `gatsby-background-image`.

Let's get this working again (and further this packages path to `v1.0.0` : )!

**Comment by kimfucious** [comment]
Ha ha!  You have a way with words!

Cornicopious is a pun, or rather, a _portmanteaux_ of copious and cornucopia.  Sometimes, I say silly stuff.  Mea culpa 😉

**Comment by timhagn** [comment]
*g* Thanks a lot for the flowers : ) - and no sweat, I was in now way offended, just amused about Wikipedia's use of "overzealous" in this context.
And I should be giving myself a facepalm now, "cornucopia" in your portmanteaux slipped my mind ^^.
Btw., before the following slips my mind, too: I meanwhile have created an `useMutationObserverRef()` hook in `gbitest`, to be able to watch the state transitions through a element reference, and cloned it onto my hosting at [gbitest.timhagn.com](https://gbitest.timhagn.com/). The issue you demonstrated is sadly visible there, too (at least with Slow 3G throttling).
Should you be interested in the hook as well as helping in mapping the states, feel free to clone [`gbitest@map-gi-states`](https://github.com/timhagn/gbitest/tree/map-gi-states); the hook is available under [`src/components/useMutationObserverRef`](https://github.com/timhagn/gbitest/blob/map-gi-states/src/components/useMutationObserverRef.js) for the moment.

**Comment by kimfucious** [comment]
Regarding your findings:

I did say, "semi" clean" 😉

You could just remove those font imports from layout.js, as they're not used in the demo/repo.  I'll do that on my side, as well.

I do live in Thailand, but my Internet connection is a hell of a lot better than Fast 3G and, yes, I am publishing to a free tier on Surge for the demo.  

But, I have to ask:  should that really matter?  The site will eventually be hosted on Netlify (probably free as well).  Will the plugin "not flash" only on performant host providers and small image files? 🤔 

I had a look see at gbitest.timhagn.com and noticed that the image file you're testing (gatsby-astronaut) is relatively small compared to the ones that I've setup on the Surge demo.

When I look at the network waterfall now (after not using 100 quality), I'm seeing much smaller file sizes downloaded, however, the flashes are there (for me, with the demo I set up.)  

Maybe if you crank up the image sizes, you'll also see what I'm talking about?

**Comment by timhagn** [comment]
Definitely no offense meant! Just noticed that my cheap static internet hosting was faster than surge (when looking at their subscription prices mine is ~9 times cheaper oO), so I mentioned it ; ).

Of course the flashes matter, I don't want to ship a broken product to devs!

And as written above: "The issue you demonstrated is sadly visible there, too", pertaining my [`gbitest`](https://gbitest.timhagn.com/) site - with Cache disabled and even only Fast 3G throttling one can see it there quite clearly  vis à vis a `gatsby-image` on the right (how it should fade in), even though the images are small (I added an additional backgroundColor of `#0f0` to make it even more eye-catching). The gatsby-astronaut is a child `gatsby-image`, so of no special interest ; ).

So, definitely sorry for the misunderstanding (to make it even more clear that I'm working on this issue I just set the Bug label : )! Let's get this fixed!

**Comment by kimfucious** [comment]
Awesome sauce!  Kindly let me know if/how I can help further.

**Comment by kimfucious** [comment]
IMHO, the true test would be ramming a few 6MB unsplash photos through the ringer to see what happens.

**Comment by timhagn** [comment]
Pew, good that's cleared up : ).
Do you know the MutationObserver API a little? Cause I'm still trying to find a concise way of documenting the transition changes in `gatsby-image` with the help of the aforementioned hook.

**Comment by timhagn** [comment]
> IMHO, the true test would be ramming a few 6MB unsplash photos through the ringer to see what happens.

Well, the effect of the bug is visible as is, without the need for such (for the web) huge images, or are you speaking about the image "minification" process?

**Comment by kimfucious** [comment]
Hey, Tim.

From experience, I'm just used to "cranking it up to eleven" (Google Spinal Tap) when testing things.

When looking at the big picture, we are--after all--looking to display background images, and many folks will opt toward large images to do so, hoping this plug in will do the magic is has the potential to do.

Do.. do.. do... Just a thought.

Keep on truckin' 😉

**Comment by timhagn** [comment]
As initially stated, the only magic `gbi` does, is lazy loading and the (ad hoc buggy) transitioning. The groundwork (resizing / minifiying / converting images) is done by `gatsby-plugin-sharp` & `gatsby-transformer-sharp` respectively.
Maybe I should make this clearer in the docs % ).

**Comment by timhagn** [comment]
And on we go : ). Though I haven't created a full fledged mFSM now, we're one step further with the release of `gatsby-background-image v0.4.3`.
On both pages, [yours @ devserv.timhagn](https://devserv.timhagn.com/) as well as [gbitest](https://gbitest.timhagn.com/) no background-flickering should be seen any more - I only noticed a image jump in the end when throttling to Slow 3G, which I'm gonna investigate further.
Please test and report  - or even better, should you be satisfied with it's behavior for the moment and would want to do the honors, feel free to close this issue ; ).

**Comment by timhagn** [comment]
Hi @kimfucious,
I just published `v0.5.0` which should solve the issue of flickering and jumping images once and for all
(it now has a "mFSM" ; ).
I updated both tests sites on my hosting with it and even with Slow 3G no unwanted effects occur : ) -
the page takes still ~5s to load with throttling, though that might be because both your images (on the first screen and the second one) get loaded up simultaneously, which might perhaps be an issue 
with `react-scroll` and their usage of the IntersectionObserver API(?).
For me this issue at hand would be solved for the moment, or what do you think?
Greetz,
Tim.

**Comment by kimfucious** [comment]
Hi @timhagn , you're awesome!

I'll test it out and let you know soonest.

Best,

Kim

**Comment by timhagn** [comment]
Hi @kimfucious,

during a moment of epiphany this afternoon, I realized that `gbi` didn't really lazy-load most of times... The reason is simple but wasn't obvious: A js `Image()` object starts loading as soon as **any** of the properties `src` (so far so good) or `srcSet` (not that obvious) are set, **and** even when the image is added to a picture-element's sources (this one bit us)!
So I split the `createPictureRef()` function in two and predictable lazy-loading, here we go : ).
`gatsby-background-image` now is at `v0.5.2` and the effect is clearly visible with "Fast 3G" on your demo page [here @ mine hosting](https://devserv.timhagn.com/) - though I had to resize the first section to `130vh`, lest the browser would load the second image stanta pede. The reason might be the same as in [this issue @ `gatsby-image`](https://github.com/gatsbyjs/gatsby/pull/13816), which I'm gonna tackle, as soon as it's greenlighted there (or even beforehand, as background images might tend to depend on screen size ; ).

Best,

Tim.

**Comment by kimfucious** [comment]
Hey @timhagn 

I got the time to check things out, and wow! 

I'm running 0.5.3, and there's no flashing, no extra files being downloaded, and it's lovely.

Awesome job, sir! 🚀

**Comment by kimfucious** [comment]
Actually, there is a flash to black sometimes... but it's fully tolerable.

Also, after moving the [demo ](https://gbi.abts.io/)to Netlify from Surge, there's a noticeable improvement as well.

**Comment by timhagn** [comment]
Mkay, there shouldn't be flashes of the background color any more, as it now ticks from one available image to the next : /. I can only guess, that sometimes the image reference's `currentSrc` might not be available for some reason (as I removed the fallback to `src` cause it was responsible for the jpgs being downloaded) \*thinks\*... Should you notice any intolerable flashes, please be sure to notice me - though I'm gonna investigate it later anyways ^^.
