### ISSUE TITLE
Non-static position, high z-index items within a BackgroundImage don't display correctly

### ISSUE THREAD

**Issue by pr3cast** [timhagn/gatsby-background-image#41]
## Description

If an element with a very high z-index and a non-static position is contained within a \<BackgroundImage\> tag, it will not appear on top of all elements. It happens consistently when a gatsby-image component is overlapping it, but I've found it happen with various other elements as well.

I made a demo here (demo site link inside): https://github.com/pr3cast/gatsby-background-image-z-bug

### Steps to reproduce

- Create a compoment X with a non-static position and a high z-index (like a fixed `<nav/>`). 
- Place it within a `<BackgroundImage />` component. 

### Expected result

Component X will display in front of all other elements

 

### Actual result

Component X will not display above all elements; it will fall behind some of them.

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.2.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 67.0.2
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.9.2 => 2.9.2 
    gatsby-background-image: ^0.7.2 => 0.7.2 
    gatsby-image: ^2.1.4 => 2.1.4 
    gatsby-plugin-emotion: ^4.0.7 => 4.0.7 
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1 
    gatsby-plugin-offline: ^2.1.3 => 2.1.3 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sass: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^2.1.9 => 2.1.9 
    gatsby-plugin-typography: ^2.2.13 => 2.2.13 
    gatsby-source-filesystem: ^2.0.39 => 2.0.39 
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21 
  npmGlobalPackages:
    gatsby-cli: 2.6.10
```

**Comment by timhagn** [comment]
The original issue was #8 : /...

**Comment by pr3cast** [comment]
> The original issue was #8 : /...

May bad! I looked through real quick and thought it was a different issue because the title didn't relate. I'll see what I can figure out using what's listed there. But regardless, I see that you added a fix to `v0.2.43` and had the issue closed?

**Comment by timhagn** [comment]
The "solution" for #8 was fixing the opacity to `0.99`, therefore I mentioned it. But methinks this causes the problems you brought up in this issue... Although my knowledge about CSS was greatly advanced by `gbi`, I still wouldn't call myself a "master of it's quirks", so any help would be greatly appreciated : )!

**Comment by timhagn** [comment]
Hi @pr3cast!

Took me a little longer to clone your repo and check if my first intuition about your issue being caused by the "opacity hack" introduced in `v0.2.43` with `opacity: 0.99;` as a enforced inline style setting on `<BackgroundImage />`. Am in grief and retired into my shell since last week, only slowly coming out of it again : /. 

But got around doing it and my initial thoughts where (sadly) correct:
Your issue is nearly the "opposite" of #8, but both stem from the same reason: [CSS stacking context](https://drafts.csswg.org/css2/zindex.html).
And whereas forcing a new context with `position: relative;` (needed for absolute positioning of the pseudo elements making it possible to "fade over" `background-image`s in the first place) in combination with aforementioned `opacity: 0.99;` solved the issue of having another context in parent elements (like with `flex` or `grid`, though every change of stacking contexts in parent elements should break `gbi` without it), it then of course breaks the children's contexts : /.

Removing the opacity from `gbi` (hard to do for releases % ) or setting (in your case):
```js
const PageWrap = styled.div`
	display: block;

	.gatsby-image-wrapper {
		opacity: 1 !important;
	}
// ...
`
```
fixes it for the moment. 
But that's a workaround I'd rather wouldn't want to have in the README...
Played around a little with parsing classes in child elements for changes in stacking contexts last night, but couldn't find an easy way to do it in `node` during Gatsby's build phase (and I guess the initial TTI of `gbi` would be heavily impacted if we parsed through all child element classes during construction / mount phases)...
Should you know of any js CSS lib that doesn't rely on `window.document` and its (various) StyleSheet helpers, I'd be only to willing to change to it from my homespun `BackgroundUtils.js` - till then I'd be only too willing to take advice : |...

Greetz,

Tim.

**Comment by timhagn** [comment]
Hello @pr3cast,

good news, it's solved! I had completely forgotten about `z-index` having the possibility of `auto` (shame on me % )! Wrapped the children in a `div` with it and tried it directly in my clone of your repo.
Worked : ). It's published as `v0.7.4`, would you mind testing it in your project?

Should your issue be solved, you may of course have the honors of closing this : )!

Greetz,

Tim.

**Comment by timhagn** [comment]
Damnit, shouted to early : /. Forgot to remove my workaround mentioned before. Still no change, 
`z-index: auto;` notwithstanding : (.

On it.

**Comment by timhagn** [comment]
Nope, giving up for today. Seems the spec is against us. Thought bout adding an option switching 
opacity: 0.99` on and off, though I rather guess, neither yours nor @EricSSartorius old issue are really just "edge cases". So it's hard to decide : /. If something comes to your mind I'd be too happy when you'd let me know, @pr3cast!

**Comment by pr3cast** [comment]
Sorry for the late reply, but I'll check out all the solutions/workarounds you've talked about this weekend. Thanks for the help!

**Comment by timhagn** [comment]
Hi @pr3cast!

As most other ways would either get in conflict with Reacts' "Top-Down" approach (like checking the parent for `display: flex` or `display: grid`) or be quite computationally expensive (like going through all childrens' styles & classes equally looking for a stacking context changing property as `position: fixed`).

So I simply settled for adding a new option: [`preserveStackingContext`](https://github.com/timhagn/gatsby-background-image/tree/master/packages/gatsby-background-image#additional-props), defaulting to false, which deactivates the "opacity hack" if set to `true`.

Should the just published `v0.7.5` suffice for the moment (I of course tested it with your repo), you may gladly have the honor of closing this issue (Though I'd be still open to PRs : ).

Best,

Tim.

**Comment by timhagn** [comment]
As PR #46 broke handling of CSS styles for multiple images, I rectified it in `v0.7.6`.

**Comment by pr3cast** [comment]
Hello, 

awesome! I'll close. Thanks for the help.
