### ISSUE TITLE
Some utility class names are not escaped which breaks

### ISSUE THREAD

**Issue by Anahkiasen** [timhagn/gatsby-background-image#49]
Related-ish to https://github.com/timhagn/gatsby-background-image/issues/40

## Description

When using some Tailwind classes such as `w-1/4`, the package reuses them as is instead of escaping them which generates invalid CSS:

```css
// Expected
.main-image.w-1\/4:before,

// Generated
.main-image.w-1/4:before,
```

### Expected result

The generated selectors apply to my element

### Actual result

The generated selectors do not apply to my element

---

I linked #40 because when I learned how the package works underneath I was very surprised, and it took me some time to track why things would break as soon as I'd add a class name. I don't think it was such a good idea to remove unique IDs for the background images, using the classes on them just seems extremely error prone as you trust the consumer of the package to give unique class names to each image which... is the opposite of what a class is for.

Why not simply add an `id` prop since that's a unique HTML attribute and make it mandatory? Then you could just target `#foobar` which would be guaranteed to target this element specifically, would that solve the issue? I don't believe relying on user class names is very future proof, that or the documentation needs to be much clearer on the constraint around class names being unique. :/

**Comment by timhagn** [comment]
Hi @Anahkiasen,

as I haven't used `tailwindcss`, I don't really know why their classes should be escaped. So I quickly searched their docs and the only thing that came up is `tailwindcss`'s inbuilt `e()` escape function [here](https://tailwindcss.com/docs/upgrading-to-v1/#escape-the-class-portion-of-any-custom-variants-you-have-created) for custom variants. Did you talk about that?
---
Pertaining your thoughts about the usage of `classNames` not being future proof I can't concur.
Using only the `id` prop for styling purposes instead of classes would break usage with CSS-in-JS libraries like `styled-components`, or you'd need a wrapper Component which targets the element as you mentioned with `#foobar`.
Though of course you can still target it in CSS by it's `id`, which prop was available since the beginning (taken over from `gatsby-image`).

How did you come to think `classNames` have to be unique or "unique ID"s where removed? With #29 a fix was introduced for [Multiple Instances of Same Component](https://github.com/timhagn/gatsby-background-image#multiple-instances-of-same-component), which should the "unique" issue...

But I'd definitely be happy should you have an idea how this could be clarified in the docs : )!

Best,

Tim.

**Comment by tomnightingalegithub** [comment]
Hi Tim,

Thanks for putting together the plugin. 

I just wanted to join in on this conversation. I'm also using Tailwind, and after looking into the docs for gatsby-background-images I'm wondering how I'd apply a background image.

`<BackgroundImage
                        fluid={props.data.ourImage.childImageSharp.fluid}
                        className="bg-multiply bg-cover bg-center md:w-1/2 lg:w-2/5 min-h-screen p-10 py-16 md:p-16 lg:p-20 flex flex-wrap flex-col justify-between bg-navy-600 text-beige-100"
                      >`

As you can see, there's a fair few classes on my element, but the colons and slashes are causing the rendered CSS to fail as they're not being escaped.

You mentioned a classId, and I saw in another issue that you suggested using multiple classes?  
How would I go about adding in the classId? 

Any help greatly appreciated :)

**Comment by timhagn** [comment]
Hi @tomnightingalegithub,

thanks for your small usage example of `<BackgroundImage />` with Tailwind classes, couldn't really fathom before why the heck Tailwind would use "illegal" characters for CSS class names (sorry, @Anahkiasen, just didn't have enough info to go on from your OP ; ). 

Had another look at the W3C specs, that's why I say illegal - and there's sadly only a [working Draft](https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape) for `CSS.escape` in the Web API according to MDN and their given Polyfill is quite large (both of which probably wouldn't work during the `build` process anyway).

PostCSS sadly won't work either, as far as I've seen, as `gbi` _has_ to create the `:before` & `:after` pseudo-elements on the fly while the different "stages" of the fluid / fixed images become available.

The `classId` was (still is, but considered deprecated as stated in the [README](https://github.com/timhagn/gatsby-background-image/tree/master/packages/gatsby-background-image#deprecated-styling)) a workaround stemming from the earliest versions of `gbi`, before I got CSS-in-JS styling working...

Have to say I'm at a loss concerning Tailwind at the moment and don't know if this really is easily solvable without exploding the package size : /.

Would need help myself to get a grip at this issue...

**Comment by tomnightingalegithub** [comment]
Hi Tim,

Thanks for your response; Glad I could help you understand the original question.

I've got the following using `classId:`

`<BackgroundImage
                            className="bg-cover bg-center py-40 w-full md:w-1/2 md:py-0"
                            fluid={props.data.eslandCare.childImageSharp.fluid}
                            classId="a-unique-class">
                        </BackgroundImage>`

This generates a class on the element: `gatsby-background-image-a-unique-class` but then the CSS is attributed to the div with all class names: 

`.bg-cover.bg-center.py-40.w-full.md:w-1/2.md:py-0:before,
.gatsby-background-image-a-unique-class:before,
          .bg-cover.bg-center.py-40.w-full.md:w-1/2.md:py-0:after,
.gatsby-background-image-a-unique-class:after {
}
`

Is there any way to isolate the class so it targets just `gatsby-background-image-a-unique-class`?

**Comment by timhagn** [comment]
Hi Tom(? don't want to write your GitHub handle all the time ; ),

really thinking about an additional workaround for such use cases, but as you'd probably want to have the styles of classes like `bg-cover`, `bg-center` and suchlike applied to the pseudo-elements as well (or do I err?), no easy one comes to mind.

Have to stop working for tonight, as I have a meeting with a potential client tomorrow (and as it's already past 11 pm here in Vienna I need some time to chill out before forcing myself going to bed ; ),
but gonna sleep over it.

Should any of you come up with a probable solution, I'd be happy to give it a try : ).

Now I'm gonna call it a night, so have a good one, too : )!

Best,

Tim.

**Comment by tomnightingalegithub** [comment]
Hi Tim,

Ha, feel free to call me Tom!

Really appreciate you coming back to me again on this one. I've been racking my brains about how we might be able to get over the issue.

I'll have a think about it over night and see if I can come up with a few ideas.

Cheers

**Comment by tomnightingalegithub** [comment]
Hi Tim,

Just wanted to give you an update. I've managed to find a work-around for the tailwind classes not escaping and causing BackgroundImage to fail to render.

Instead of adding the Tailwind media query classes onto the BackgroundImage component, I've given the component a unique class and then referenced the required media queries through my CSS file instead. It's not perfect, but it's working!

Example below:

**Before**
`
<BackgroundImage className="bg-cover bg-center py-40 w-full md:w-1/2 md:py-0" fluid={props.data.ourImage.childImageSharp.fluid}> </BackgroundImage>
`

**After**
`<BackgroundImage className="unique-class bg-cover bg-center py-40 w-full" fluid={props.data.ourImage.childImageSharp.fluid}> </BackgroundImage>
`

**global.css**
`
@screen md {
  .unique-class {
    @apply w-1/2;
    @apply py-0;
  }  
}
`

This would also be a suitable workaround for repeating components with different background images as we can still dynamically pull the background image from graphQL.

I found this in the Tailwind docs:
https://tailwindcss.com/docs/functions-and-directives/

Thanks for your help & response last night. Hopefully this might go some-way to providing a solution for others :)

Cheers,
Tom

**Comment by timhagn** [comment]
Hi @tomnightingalegithub  / Tom,

sorry I didn't answer earlier, but this week was like -0 to 100+ to me, gig and emotional related % ).

Your workaround seems definitely sound and suitable! Although it's still a workaround, which we either should mention in the docs or find a way around. Tailwind seems to gain some traction in the Gatsby world, so we should cater for it, methinks. 

The only other thing my mind was able to come up with through all this stress - 3 meetings with 3 different possible clients in 3 days, and all (at least 2 of them) surprisingly nailed, as it seems (still have to bend my head around it, cause `gbi` was one of the reasons % ) - is "just" stripping the classes with, let's say 'non-conforming' instead of 'illegal', names from the pseudo-elements. 
Cause as far as I gathered (correct me, if I'm wrong) most of them don't directly concern the background images, but only the wrapping element, which would get processed by postCSS...

Attaching global styles automatically would be kinda hard (especially during the build process), but any advice would be more than welcome!

 - @mxstbr, how do you do this in `styled-components` if you would be so kind to answer? Have read through the code base, but most of it doesn't apply to dynamically induced styles... -

Now I'm chilling out a little, but this issue definitely won't be left untended!

Thanks for your efforts, Tom!

Best,

Tim.

**Comment by tomnightingalegithub** [comment]
Hi @timhagn,

Congrats on landing at least two of the gigs! 

You're correct, the majority of the classes in the example above don't concern background images. bg-multiply is a class I created to add a blend-mode to the background image, whereas bg-cover and bg-center are sizing & positioning classes that are pulled from Tailwind.

I think if you stripped the non-conforming classes from the :pseudo elements, this should be ok. I'm struggling to picture an example where this wouldn't work. The only eventuality I can think of right now is whether a Media Query such existed to change background properties. 

For example:
`className="bg-cover md:bg-contain`

I'm not sure this would be an issue, but thought I'd include the use-case just in case.

Cheers

**Comment by timhagn** [comment]
Hi Tom,

sadly still didn't find the time to look into this, but definitely haven't forgotten bout this issue : )!

Best,

Tim.

**Comment by timhagn** [comment]
Hi @tomnightingalegithub / Tom & @Anahkiasen!

Have definitely not forgotten this issue and gonna try to work on it this weekend, but still, no promises % ). Any help would be still welcome (PRs \*wink wink\* ; )!

Best,

Tim.

**Comment by timhagn** [comment]
Hi @tomnightingalegithub / Tom & @Anahkiasen!

Finally (though not promised ; ), I came round at having a closer look at this.

As it seems to me that the default characters of Tailwind CSS that have to be escaped are `:` and `/` unless you are using plugins for it, I put in a few hours and added an `escapeClassNames()` function for the pseudo-Elements as well as a `specialChars` plugin option. 

With those it was now possible to use Tailwind classes on `BackgroundImage` (I didn't try plugins, though % ). More Information in the README at [Tailwind CSS and suchlike Frameworks](#tailwind-css-and-suchlike-frameworks).

Published in `v0.8.8`, would you be so kind as to test it and close this issue should it solve the initial problem?

Best,

Tim.

**Comment by tomnightingalegithub** [comment]
Hi @timhagn 

Sorry for not getting back to you sooner, I've been away from the screen for a few weeks enjoying what's left of the UK sunshine!

I've just tested the new update and it all seems to work fine. I really appreciate you looking into this and I'm glad you managed to come up with a solution.

Thanks a lot!

**Comment by timhagn** [comment]
Hi @tomnightingalegithub / Tom,

hey, no prob, I took my time to finally lay hands on it ; ).
Great that it solves the issue : )!

@Anahkiasen would you be so kind to chime in? Else I'm gonna close this on Monday at the latest.

Best,

Tim.

**Comment by Anahkiasen** [comment]
Sorry yeah I still need to check this again, will try to give it a quick look this weekend

**Comment by Anahkiasen** [comment]
Seems to work perfectly on 0.8.11 👍

**Comment by timhagn** [comment]
Then feel free to close it, the honor is all yours : ).
