### ISSUE TITLE
A linear-gradient overlay isn't working in IE11

### ISSUE THREAD

**Issue by tremby** [timhagn/gatsby-background-image#50]
### Description

I'm overlaying a linear-gradient on a background image, and it's working in recent browsers but not in IE11.

### Steps to reproduce

Do something like.

    <BackgroundImage fluid={['linear-gradient(to bottom, transparent, white)', myBackgroundImgFluid]} ...

### Expected result

Tinted overlay which gets more opaque towards the bottom, in all browsers.

### Actual result

It works fine in Firefox and Chrome for example, but not in IE11.

When I inspect the ::before element in Firefox it has the `background-image` property I expect -- the linear gradient and then an image.

When I inspect the ::before element in IE11, it has two `url()` backgrounds. The second one looks correct (it's the image, which is showing) but the first is `url('http://10.0.0.77:9000/')` where I'd expect to see the gradient. This is the URL the browser is currently pointed at.

I notice that the background-image property in the ::after element looks fine -- it has a linear gradient and then an image. This is the blur-up one though, I think -- it's hidden by the ::after. I wonder why one is fine and the other isn't...?

### Environment

```
  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
    Shell: 5.4.2 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/bin/node
    Yarn: 1.15.2 - /usr/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Firefox: 68.0
  npmPackages:
    gatsby: ^2.13.9 => 2 
```

**Comment by timhagn** [comment]
Hi @tremby (& @cobyhausrath),

am at a slight loss here, as according to [Microsoft's Docs](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/hh673532(v=vs.85)) this kind of `linear-gradient()`s should work since IE10 oO...

Pertaining the duplicate `url()`s in IE11 I have no clue at the moment, would it be possible for you to give me some example code (or even better an example repo) where I could get a closer look at this behavior?

As you seem to be using WSL according to your given `gatsby info`, which sadly doesn't show all plugins used with Gatsby, this would definitely help me in zeroing in on your issue in a VM (am on Linux) : ).

Best,

Tim.

**Comment by tremby** [comment]
Hoping to find time to give an example repo soon.

What is WSL?

**Comment by timhagn** [comment]
Hi @tremby / Bart,

WSL is "Windows Subsystem for Linux" - and just a blind guess from my part, as your `gatsby info` shows `OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)`, though your issue is an IE11 one ^^.

A repo really would be great : )! Should maybe update the GitHub templates for the time being "expecting" these, as I just took on a new freelance subcontractor project and time is sparse % ).

**Comment by timhagn** [comment]
Hi @tremby / Bart,

did you already find the time creating a repo? Still couldn't fathom how to replicate the behavior you mentioned...

Best,

Tim.

**Comment by tremby** [comment]
I develop with such machines as the info given above, and I test in IE with VMs and with Browserstack. Never used WSL; don't have a Windows machine.

OK, here you go: https://github.com/tremby/linear-gradient-test

Deployed at http://linear-gradient-test.surge.sh/

Screenshot on Firefox on Linux:

![firefox](https://user-images.githubusercontent.com/199635/63047804-1320ca80-becd-11e9-9176-db3fc26f28a7.png)

Screenshot on IE11 via Browserstack:

![ie11](https://user-images.githubusercontent.com/199635/63047824-1c119c00-becd-11e9-8b91-afb0c1263b29.png)

**Comment by tremby** [comment]
See this screenshot in IE11 with dev tools. See the highlighted rule. (I don't know why it's crossed out; it *is* active; if I toggle it off the background becomes plain grey.)

![ie11-2](https://user-images.githubusercontent.com/199635/63048840-3d738780-becf-11e9-8766-7ab752508dcd.png)

**Comment by itwasmattgregg** [comment]
So it looks like the ::before element which has the higher z-index actually doesn't have the linear-gradient property on it, instead it looks like this:
`background-image: url('http://linear-gradient-test.surge.sh/'),url('http://linear-gradient-test.surge.sh/static/9e3d7500430e2c3bf00e76a486f1aad9/98569/art-artisan-artist-2378538.jpg')`

This is why you see the gradient for a short second before in gets covered up by the higher resolution image. That first url should instead be a linear gradient. I'll have to dig a little to see where this problem might be in the background code. @timhagn Do you know what might be going on?

**Comment by tremby** [comment]
Exactly, as pointed out in the "actual result" section of my original post :wink: just with a different hostname.

**Comment by itwasmattgregg** [comment]
Sorry I didn't see that. I'm not sure why the code that helps with urls in styles is messing this up on IE only. I'll try to look into it more.

**Comment by itwasmattgregg** [comment]
I tried using the es5 package as well but that didn't seem to solve anything or change the style output. Something screwy is happening when building up that :before style from an array.

**Comment by timhagn** [comment]
Hi there,
am on the move right now, but still looked ar your example repo, @tremby. Have no idea atm, why FF is showing them correctly and IE11 doesn't...
Gonna try looking at it tomorrow, though no promises, have two other Projects in the pipeline.
Thanks @itwasmattgregg for helping out : )!
Best, Tim.

**Comment by timhagn** [comment]
Hi again,

finally have gotten around debugging (as much as `console.log()` may be called thus ; ) through your repo on a Windows VM @tremby. Now I already know in which vicinity the annoying little bugger is hiding - before returning `nextImage` on line 289 of [`ImageUtils.js`](https://github.com/timhagn/gatsby-background-image/blob/f0a85f8e017db16a3e5c70d4f9b7bfaf4656ce61/packages/gatsby-background-image/src/ImageUtils.js#L289) everything is in order - but I still have to dig deeper what IE has against any of the used functions : /. Will get back to you (both) when I know more tomorrow. What astounds me the most is that with another site of mine and a `linear-gradient` added in `gbi` everything works as it should oO...

Have a nice night, best,

Tim.

**Comment by timhagn** [comment]
Hi @tremby (& @itwasmattgregg),

just published `gbi(-es5)` @ `v0.8.5` which should rectify this issue : ).
At least at my place on a Windoze 10 VM with IE11 it now looks correctly (both in develop & build):
![IE11 in VM](https://user-images.githubusercontent.com/12220779/63228723-5ba2f580-c1f7-11e9-8e18-937f22668a5d.jpg)

As I already wrote two days ago (didn't find any time yesterday, so did id this evening), the problem was in the vicinity of the `getCurrentFromData()` - only not the one on line 289 as stated above, but (of course in IE11) the one on line 299 (getting the `src` from `imageRef`). Just had to change 
the clause 
`if (propName === 'currentSrc')` 
to 
`if (propName === 'currentSrc' || propName === 'src')`
and it started working % ).
That's also the explanation, why it worked in FF & Chrome beforehand - they of course go for `currentSrc`, not `src` ^^.

Would you be so kind to test it on your side, @tremby?

Thumbs pressed it's solved, you may of course have the honors of closing your issue : ).

Best,

Tim.
P.S.: Sorry for implying you would work on a windoze machine, just got a few `gatsby info`s like the one you gave from windows machines (on my Linux station it lists all of Gatsby's dependencies, not only `gatsby-background-image` ; ).

**Comment by tremby** [comment]
Works for me. Thank you!

**Comment by timhagn** [comment]
That's great news : )! You're welcome, of course.
