### ISSUE TITLE
Javascript disabled 

### ISSUE THREAD

**Issue by mandarinezi** [timhagn/gatsby-background-image#64]
Image keeps blurred with javascript disabled. It's not case with gatsby-image

**Comment by timhagn** [comment]
Hi @mandarinezi,

might you wanna elaborate a bit more? Or at least provide an example and `gatsby info` as asked for (and System / Browser used)
Cause I haven't run into this - without JS, the `noscript` element usually provides a simple `.jpg` fallback...

Best,

Tim.

**Comment by timhagn** [comment]
Hi @mandarinezi,

thanks for noticing this bug! It was introduced in `v0.8.5` while fixing #50 (incorrect `src`). Fixed in the just published `v0.8.7` : ). Would you mind giving it a spin - and should it solve the issue for you, too, you of course have the honors of closing this one ; ).

Best,

Tim.

**Comment by timhagn** [comment]
**Now we are at `v0.8.8` making this possible on build to (Forgot to test that before publishing `v0.8.7` % ).**
