### ISSUE TITLE
gatsby-background-image generates giant project size

### ISSUE THREAD

**Issue by emilyaviva** [timhagn/gatsby-background-image#65]
## Description
I'm starting a new project in Gatsby. I am using `gatsby-background-image` with an 8 MB Unsplash image. This is the only image in the project, aside from a `gatsby-image` of the project logo. When I run `gatsby build`, the `public` directory size is 115 MB and many different copies of the Unsplash image were created in the `public` directory. Compared to when I run `gatsby build` on the branch without the `gatsby-background-image`, where the `public` directory is only 2.3 MB.

### Steps to reproduce
Project repo: https://github.com/emilyaviva/seattlemoshav.org

Run `gatsby build` on the `master` branch (which uses `gatsby-background-image`) and compare its `public` output to the same command run on the `no-background-image` branch.

### Environment
```
  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 12.9.0 - ~/sw/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/sw/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.2
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.14.2 => 2.14.2 
    gatsby-background-image: ^0.8.5 => 0.8.5 
    gatsby-image: ^2.2.14 => 2.2.14 
    gatsby-plugin-manifest: ^2.2.9 => 2.2.9 
    gatsby-plugin-offline: ^2.2.10 => 2.2.10 
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3 
    gatsby-plugin-react-helmet: ^3.1.5 => 3.1.5 
    gatsby-plugin-sharp: ^2.2.18 => 2.2.18 
    gatsby-plugin-typography: ^2.3.5 => 2.3.5 
    gatsby-source-filesystem: ^2.1.18 => 2.1.18 
    gatsby-transformer-sharp: ^2.2.12 => 2.2.12 
  npmGlobalPackages:
    gatsby-cli: 2.7.40
```

**Comment by mandarinezi** [comment]
this is form gatsby-image docs...background gatsby image uses this also:
Two types of responsive images
There are two types of responsive images supported by gatsby-image.

1. Images that have a fixed width and height
2. Images that stretch across a fluid container
In the first scenario, you want to vary the image’s size for different screen resolutions — in other words, create retina images.

For the second scenario, you want to create multiple sizes of thumbnails for devices with widths stretching from smartphone to wide desktop monitors.

To decide between the two, ask yourself: “do I know the exact size this image will be?” If yes, it’s the first type. If no and its width and/or height need to vary depending on the size of the screen, then it’s the second type.

Im newbie too,but i know that only one will be downloaded by user if you use fluid,
i dont know how to create just one image using fluid type and strech it to fit all screen sizes..

**Comment by timhagn** [comment]
Hi @emilyaviva & @mandarinezi!

First off, that's not `gatsby-background-image` doing the inflation of your `public` folders, as it only comes in, when all is processed and done.
Maybe I should reduce the `maxWidth` in the examples, `4160` targets (at the max) 4K, so that could be a little ambitious ^^. 

You'd have the same result when using a `gatsby-image` with the same GraphQL query for the image, though. Cause the process is like:
 `YOUR_IMAGE.JPG/.PNG/.etc` => 
`gatsby-plugin-sharp` creating at the least 4 images, one for each size as `.jpg` per default, `_withWebp` doing 4 more WebP images more - and `SVG` or `base64` not even counted in right now - but you can do the math =>
`gatsby-transformer-sharp` providing the GraphQL transformations for the images the plugin provides and you access with the queries =>
`gatsby-(background)-image` only viewing the resulting image (and in modern browsers definitely only showing the most fitting for the Users' Browser to download).

Don't know why you'd want only one image to stretch @mandarinezi, cause that's kind of the opposite to "optimized" - having the user in mind, not your `public` folder.

Am gonna close this issue now, as it really has nothing to do with `gbi`, really...
Though I'm still gonna watch this thread for further questions : ).

Best,

Tim.
