### ISSUE TITLE
Webp format not scaling

### ISSUE THREAD

**Issue by auto200** [timhagn/gatsby-background-image#70]
Images are not scaling properly (quality is too small, loads like 30kb webp and not changing) when using `GatsbyImageSharpFluid_withWebp` fragment but everything works fine using `GatsbyImageSharpFluid` (like 1mb jpg for fullhd). Haven't noticed it for a while because I was working on mobile version :>
So here's my query:
```
const data = useStaticQuery(graphql`
    query {
      MM: file(relativePath: { eq: "offer/image.jpeg" }) {
        childImageSharp {
          fluid(quality: 90) {
            ...GatsbyImageSharpFluid_withWebp
          }
        }
      }
   }
`);
```
then i pass it to component:
`<Tail bgSrc={data.MM.childImageSharp.fluid} />`
and in the component I render it out in styled BackgroundImage component like this:
`<StyledBackground fluid={bgSrc} fadeIn={false} />`

Im pretty new into gatsby, gatsby-background-image and graphql world so it might be my silly mistake but it confuses me that one way it works but other doesn't. Tested on chrome  76.0.3809.132 and firefox 68.0.2

Already cleaned cache and updated gatsby to newest version

from `gatsby info`
gatsby: ^2.15.2 => 2.15.2
    gatsby-background-image: ^0.8.9 => 0.8.9
    gatsby-image: ^2.2.16 => 2.2.16
    gatsby-plugin-manifest: ^2.2.13 => 2.2.13
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-react-helmet: ^3.1.6 => 3.1.6
    gatsby-plugin-sharp: ^2.2.19 => 2.2.19
    gatsby-plugin-styled-components: ^3.1.4 => 3.1.4
    gatsby-source-filesystem: ^2.1.19 => 2.1.19
    gatsby-transformer-sharp: ^2.2.13 => 2.2.13

**Comment by auto200** [comment]
Fresh day, computer restart, hot shower. i don't know what helped but part of the problem was that if you don't specify max width in the query `fluid(quality: 90, maxWidth: 3000)` it sets default to 800. Still don't know why it worked diffrently for `GatsbyImageSharpFluid` and `GatsbyImageSharpFluid_withWebp`

**Comment by timhagn** [comment]
Hi @auto200,

sry I didn't get around earlier to reply - but great to hear you could solve it yourself : )!
Such Issues I like the most, those that solve themselves ^^.

All I can point you to about the difference for JPG and WebP is that the `sharp` image processing library used in `gatsby-plugin-sharp` is not the only one involved in creating JPEGs, there's `imagemin`, too. And JPEGs have been around some time longer than WebP, so that's probably the cause they cause less "artifacts". After all they are "only" lossy, compared to WebP which employs both lossy and lossless compression.

Again, great you could solve this : )!

Best,

Tim.
