### ISSUE TITLE
unoverridable enforced 0.99 opacity causing discoloration

### ISSUE THREAD

**Issue by D-Nice** [timhagn/gatsby-background-image#72]
## Summary
Is there a reason the encompassing div has a 0.99 opacity value set that apparently cannot be overriden through the `style` prop?

## Relevant information

Wondering why this is the default, and seemingly not overridable, if I'm missing some important function behind it. It would seem to make more sense to not have it as a default if it serves no important purpose, as it has the effect of discoloring child elements, and thereby complicates what would effectively be a seamless transition from regular css background image to gatsby-background-image.

**Comment by timhagn** [comment]
Hi @D-Nice,

yup, you missed something which I maybe should point out more clearly in the docs:
The `opacity: 0.99` is a CSS-Hack to preserve the stacking context and is overideable since `v0.7.5` as explained [here in the README](https://github.com/timhagn/gatsby-background-image/blob/master/packages/gatsby-background-image/README.md#additional-props) ; ).

Hope this solves your issue : ). So, should it, please feel free to close it.

Best,

Tim.

**Comment by D-Nice** [comment]
Thanks for taking the time to point that out and my fault for missing it. May be useful to point out in the gatsby docs, as I was mostly referencing from there if you decide to do so :).

**Comment by timhagn** [comment]
For a moment after reading that you got me thinking that the Core Team had included `gbi` into the 'Handling Images' Docs % ). Or where did you gather your references, what am I missing now ^^? Thanks in advance and of course you're welcome : ).
