### ISSUE TITLE
gatsby background image flashes

### ISSUE THREAD

**Issue by Prenoult** [timhagn/gatsby-background-image#83]
Hello I am encountering an issue using **gatsby-background-image**.

I am trying to implement a contact form (with a Gatsby background image) and I am using the react `onChange` event in my `<input/>` tag. Everything works well but the `onChange` event  update the react component and the image background displays a reload effect and when the user write a long word in the input field, the background seems to flashes due to the reload effect.

Moreover, this issue does not occur with the **official plugin gatsby-Image**. 

Please, what can I do ?

**Comment by timhagn** [comment]
Hi @Prenoult  / Paul,

mkay, usually `gbi` shouldn't go through the reload effect on a rerender oO. 
But why does your whole component rerender on every `<input />` change? For the moment you might try encapsulating them in their own components, so React only will rerender these instead of the whole form(?) `onChange`. 
But am gonna try having a look at it (am quite full with work atm % ) - might you have some code to make it easier for me replicating your issue?

Oh, and just to explain why it doesn't happen with `gatsby-image`: They are able to use the native `picture` element for images (which the browser is able to control), whereas `gbi` has to use some CSS based "trickery" to achieve the same effect ; ). Sadly there's no far reaching browser support for the CSS [`image-set`](https://caniuse.com/#feat=css-image-set) up till now : /.

Best,

Tim.

**Comment by Prenoult** [comment]
**Thank you** for your response @timhagn !

So, I just made a `<Form />` component which handle internally the `onChange` event with its `<input />` and so the parent component do not rerender on every input change. 

So **problem solved** ✅ ! That was a "newbie" question obviously, but I was surprised that `gbi` reloads every time and not `gatsby-image`.
